/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TeachersRouteImport } from './routes/teachers'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as NearbyRouteImport } from './routes/nearby'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TeachersIdRouteImport } from './routes/teachers.$id'
import { Route as ReviewBookingIdRouteImport } from './routes/review.$bookingId'
import { Route as RegisterTeacherRouteImport } from './routes/register.teacher'
import { Route as RegisterStudentRouteImport } from './routes/register.student'
import { Route as DashboardTeacherRouteImport } from './routes/dashboard.teacher'
import { Route as DashboardStudentRouteImport } from './routes/dashboard.student'
import { Route as ClassroomSessionIdRouteImport } from './routes/classroom.$sessionId'
import { Route as BookTeacherIdRouteImport } from './routes/book.$teacherId'

const TeachersRoute = TeachersRouteImport.update({
  id: '/teachers',
  path: '/teachers',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const NearbyRoute = NearbyRouteImport.update({
  id: '/nearby',
  path: '/nearby',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeachersIdRoute = TeachersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => TeachersRoute,
} as any)
const ReviewBookingIdRoute = ReviewBookingIdRouteImport.update({
  id: '/review/$bookingId',
  path: '/review/$bookingId',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterTeacherRoute = RegisterTeacherRouteImport.update({
  id: '/register/teacher',
  path: '/register/teacher',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterStudentRoute = RegisterStudentRouteImport.update({
  id: '/register/student',
  path: '/register/student',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardTeacherRoute = DashboardTeacherRouteImport.update({
  id: '/dashboard/teacher',
  path: '/dashboard/teacher',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardStudentRoute = DashboardStudentRouteImport.update({
  id: '/dashboard/student',
  path: '/dashboard/student',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassroomSessionIdRoute = ClassroomSessionIdRouteImport.update({
  id: '/classroom/$sessionId',
  path: '/classroom/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const BookTeacherIdRoute = BookTeacherIdRouteImport.update({
  id: '/book/$teacherId',
  path: '/book/$teacherId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/nearby': typeof NearbyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/teachers': typeof TeachersRouteWithChildren
  '/book/$teacherId': typeof BookTeacherIdRoute
  '/classroom/$sessionId': typeof ClassroomSessionIdRoute
  '/dashboard/student': typeof DashboardStudentRoute
  '/dashboard/teacher': typeof DashboardTeacherRoute
  '/register/student': typeof RegisterStudentRoute
  '/register/teacher': typeof RegisterTeacherRoute
  '/review/$bookingId': typeof ReviewBookingIdRoute
  '/teachers/$id': typeof TeachersIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/nearby': typeof NearbyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/teachers': typeof TeachersRouteWithChildren
  '/book/$teacherId': typeof BookTeacherIdRoute
  '/classroom/$sessionId': typeof ClassroomSessionIdRoute
  '/dashboard/student': typeof DashboardStudentRoute
  '/dashboard/teacher': typeof DashboardTeacherRoute
  '/register/student': typeof RegisterStudentRoute
  '/register/teacher': typeof RegisterTeacherRoute
  '/review/$bookingId': typeof ReviewBookingIdRoute
  '/teachers/$id': typeof TeachersIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/nearby': typeof NearbyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/teachers': typeof TeachersRouteWithChildren
  '/book/$teacherId': typeof BookTeacherIdRoute
  '/classroom/$sessionId': typeof ClassroomSessionIdRoute
  '/dashboard/student': typeof DashboardStudentRoute
  '/dashboard/teacher': typeof DashboardTeacherRoute
  '/register/student': typeof RegisterStudentRoute
  '/register/teacher': typeof RegisterTeacherRoute
  '/review/$bookingId': typeof ReviewBookingIdRoute
  '/teachers/$id': typeof TeachersIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/nearby'
    | '/sitemap.xml'
    | '/teachers'
    | '/book/$teacherId'
    | '/classroom/$sessionId'
    | '/dashboard/student'
    | '/dashboard/teacher'
    | '/register/student'
    | '/register/teacher'
    | '/review/$bookingId'
    | '/teachers/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/nearby'
    | '/sitemap.xml'
    | '/teachers'
    | '/book/$teacherId'
    | '/classroom/$sessionId'
    | '/dashboard/student'
    | '/dashboard/teacher'
    | '/register/student'
    | '/register/teacher'
    | '/review/$bookingId'
    | '/teachers/$id'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/nearby'
    | '/sitemap.xml'
    | '/teachers'
    | '/book/$teacherId'
    | '/classroom/$sessionId'
    | '/dashboard/student'
    | '/dashboard/teacher'
    | '/register/student'
    | '/register/teacher'
    | '/review/$bookingId'
    | '/teachers/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  NearbyRoute: typeof NearbyRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TeachersRoute: typeof TeachersRouteWithChildren
  BookTeacherIdRoute: typeof BookTeacherIdRoute
  ClassroomSessionIdRoute: typeof ClassroomSessionIdRoute
  DashboardStudentRoute: typeof DashboardStudentRoute
  DashboardTeacherRoute: typeof DashboardTeacherRoute
  RegisterStudentRoute: typeof RegisterStudentRoute
  RegisterTeacherRoute: typeof RegisterTeacherRoute
  ReviewBookingIdRoute: typeof ReviewBookingIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/teachers': {
      id: '/teachers'
      path: '/teachers'
      fullPath: '/teachers'
      preLoaderRoute: typeof TeachersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nearby': {
      id: '/nearby'
      path: '/nearby'
      fullPath: '/nearby'
      preLoaderRoute: typeof NearbyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teachers/$id': {
      id: '/teachers/$id'
      path: '/$id'
      fullPath: '/teachers/$id'
      preLoaderRoute: typeof TeachersIdRouteImport
      parentRoute: typeof TeachersRoute
    }
    '/review/$bookingId': {
      id: '/review/$bookingId'
      path: '/review/$bookingId'
      fullPath: '/review/$bookingId'
      preLoaderRoute: typeof ReviewBookingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register/teacher': {
      id: '/register/teacher'
      path: '/register/teacher'
      fullPath: '/register/teacher'
      preLoaderRoute: typeof RegisterTeacherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register/student': {
      id: '/register/student'
      path: '/register/student'
      fullPath: '/register/student'
      preLoaderRoute: typeof RegisterStudentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/teacher': {
      id: '/dashboard/teacher'
      path: '/dashboard/teacher'
      fullPath: '/dashboard/teacher'
      preLoaderRoute: typeof DashboardTeacherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/student': {
      id: '/dashboard/student'
      path: '/dashboard/student'
      fullPath: '/dashboard/student'
      preLoaderRoute: typeof DashboardStudentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/classroom/$sessionId': {
      id: '/classroom/$sessionId'
      path: '/classroom/$sessionId'
      fullPath: '/classroom/$sessionId'
      preLoaderRoute: typeof ClassroomSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/$teacherId': {
      id: '/book/$teacherId'
      path: '/book/$teacherId'
      fullPath: '/book/$teacherId'
      preLoaderRoute: typeof BookTeacherIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface TeachersRouteChildren {
  TeachersIdRoute: typeof TeachersIdRoute
}

const TeachersRouteChildren: TeachersRouteChildren = {
  TeachersIdRoute: TeachersIdRoute,
}

const TeachersRouteWithChildren = TeachersRoute._addFileChildren(
  TeachersRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  NearbyRoute: NearbyRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TeachersRoute: TeachersRouteWithChildren,
  BookTeacherIdRoute: BookTeacherIdRoute,
  ClassroomSessionIdRoute: ClassroomSessionIdRoute,
  DashboardStudentRoute: DashboardStudentRoute,
  DashboardTeacherRoute: DashboardTeacherRoute,
  RegisterStudentRoute: RegisterStudentRoute,
  RegisterTeacherRoute: RegisterTeacherRoute,
  ReviewBookingIdRoute: ReviewBookingIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
